# Defining the Home Assistant add-on configuration for AWS FaceRekognition
name: AWS FaceRekognition
description: AWS FaceRekognition add-on for Home Assistant
version: "2.6"
slug: aws_facereognition
url: https://github.com/Ly02032004/RekognitionFaceManager-addon
arch:
  - amd64
  - i386
  - aarch64
stage: stable
startup: application
boot: auto
stdin: true
homeassistant_api: true
host_network: true
map:
  - config:rw
image: ghcr.io/ly02032004/rekognitionfacemanager
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Web interface (if applicable)"
options:
  aws_sercret_key: ""
  aws_api_key: ""
  collection_id: ""
  mqtt_host: ""
  mqtt_port: "1883"
  mqtt_user: ""
  mqtt_pass: ""
schema:
  aws_sercret_key: str
  aws_api_key: str
  collection_id: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str
environment:
  SERCERT_KEY: "{AWS_SERCERT_KEY}"
  API_KEY: "{AWS_API_KEY}"
  COLLECTION_ID: "{COLLECTION_ID}"
  MQTT_HOST: "{MQTT_HOST}"
  MQTT_PORT: "{MQTT_PORT}"
  MQTT_USER: "{MQTT_USER}"
  MQTT_PASS: "{MQTT_PASS}"
