name: Face Addon
version: "2.0"
slug: rekognitionface_addon
description: A custom Home Assistant add-on running a Docker image from GitHub
url: https://github.com/Ly02032004/RekognitionFaceManager-addon
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface (if applicable)
image: ghcr.io/ly02032004/rekognitionfacemanager:2.0
options:
  log_level: info
