# Defining the Home Assistant add-on configuration for AWS FaceRekognition
name: AWS FaceRekognition
description: AWS FaceRekognition add-on for Home Assistant
version: "2.6.1"
slug: aws_facereognition
url: https://github.com/Ly02032004/RekognitionFaceManager-addon
arch:
  - amd64
  - i386
  - aarch64
stage: stable
startup: application
boot: auto
stdin: true
homeassistant_api: true
host_network: true
map:
  - config:rw
image: ghcr.io/ly02032004/rekognitionfacemanager
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Web interface (if applicable)"
