name: AWS FaceRekognition 
description: AWS FaceRekognition 
version: '2.0'
image: ghcr.io/ly02032004/rekognitionfacemanager
slug: aws_facereognition
url: https://github.com/Ly02032004/RekognitionFaceManager-addon/edit/master/addons
arch:
- amd64
- i386
- aarch64
stage: stable
startup: application
boot: auto
stdin: true
homeassistant_api: true
map:
  - config:rw
volumes:
  - volume: /config/face/snapshots
    container: /app/monitor
  - volume: /config/face/config.json
    container: /app/config.json
  - volume: /config/face/logs
    container: /app/logs
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface (if applicable)
