# Defining the Home Assistant add-on configuration for AWS FaceRekognition
name: AWS FaceRekognition
description: AWS FaceRekognition add-on for Home Assistant
version: "2.6"
slug: aws_facereognition
url: https://github.com/Ly02032004/RekognitionFaceManager-addon
arch:
  - amd64
  - i386
  - aarch64
stage: stable
startup: application
boot: auto
stdin: true
homeassistant_api: true
host_network: true
map:
  - config:rw
image: ghcr.io/ly02032004/rekognitionfacemanager
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Web interface (if applicable)"
options:
  aws_secret_key: ""
  aws_api_key: ""
  collection_id: ""
  mqtt_host: ""
  mqtt_port: "1883"
  mqtt_user: ""
  mqtt_pass: ""
  monitor_path: ""
schema:
  aws_secret_key: 
    type: str
    description: AWS Secret Key
  aws_api_key: 
    type: str
    description: AWS API Key
  collection_id: 
    type: str
    description: AWS Rekonigtion Collection
  mqtt_host: 
    type: str
    description: MQTT Host
  mqtt_port: 
    type: int
    description: MQTT Port
  mqtt_user: 
    type: str
    description: MQTT User
  mqtt_pass: 
    type: password
    description: AWS Secret Key
  monitor_path: 
    type: str
    description: Path Monitor Snapshot
environment:
  SECRET_KEY: "{aws_secret_key}"
  API_KEY: "{aws_api_key}"
  COLLECTION_ID: "{collection_id}"
  MQTT_HOST: "{mqtt_host}"
  MQTT_PORT: "{mqtt_port}"
  MQTT_USER: "{mqtt_user}"
  MQTT_PASS: "{mqtt_pass}"
  MONITOR_PATH: "{monitor_path}"
