name: AWS FaceRekognition 
description: AWS FaceRekognition 
version: '2.0'
image: ghcr.io/ly02032004/rekognitionfacemanager
slug: aws_facereognition
url: https://github.com/Ly02032004/RekognitionFaceManager-addon/edit/master/addons
arch:
- amd64
- i386
- aarch64
stage: stable
startup: application
boot: auto
stdin: true
homeassistant_api: true
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface (if applicable)
